---
# This playbook installs HSTR

- name: Install prerequisites
  dnf: name=hstr state=latest

- name: Extend zsh configuration
  lineinfile:
    dest={{ home_dir }}/.zshrc
    line='export HISTFILE=~/.zsh_history; export HH_CONFIG=hicolor; bindkey -s "\C-r" "\eqhh\n"'
    state=present
