---
# This playbook installs VS Code

- name: Install repo key
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Create repo config
  shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install VS Code package
  dnf: name=code state=latest
