---
# This playbook installs dotcfgs

- name: Create symlinks
  file: 
    src={{ home_dir }}/git/dotcfgs/{{ item.src }}
    dest={{ home_dir }}/{{ item.dest }}
    state=link
    mode=0600
    owner={{ user }}
    group={{ group }}
    force=yes
  with_items:
    - { src: ".gitconfig", dest: ".gitconfig" }
    - { src: ".screenrc", dest: ".screenrc" }
    - { src: ".vimperatorrc", dest: ".vimperatorrc" }
    - { src: ".tmux.conf", dest: ".tmux.conf" }
    - { src: ".vimrc", dest: ".vimrc" }
    - { src: ".zshrc", dest: ".zshrc" }
    - { src: ".tmuxinator", dest: ".tmuxinator" }
    - { src: "ssh/config", dest: ".ssh/config" }
    - { src: ".aws", dest: ".aws" }
    - { src: ".boto", dest: ".boto" }
