---
# This playbook installs dotcfgs

- name: Create symlinks
  file: 
    src={{ home_dir }}/git/dotcfgs/{{ item.src }}
    dest={{ home_dir }}/{{ item.dest }}
    state=link
    mode=0600
    owner={{ user }}
    group={{ group }}
    force=yes
  with_items:
    - { src: ".gitconfig", dest: ".gitconfig" }
    - { src: ".vimrc", dest: ".vimrc" }
    - { src: ".bashrc", dest: ".bashrc" }
    - { src: ".zshrc", dest: ".zshrc" }
    - { src: "ssh/config", dest: ".ssh/config" }
